name: "Test Collection Lists"
on:
  push:
    branches:
      - main
    paths:
      - "**"
  pull_request:
    paths:
      - "**"
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install && npx lint-staged && npm test
        working-directory: "."
